# Inclusion

We want our resources to be accessible to everyone. This means thinking about accessibility with regards to disability, language, identity, and other characteristics. This is a work in progress; feel free to suggest additions.


## Tips for text-readers

Some students need to use text readers for accessibility; others just prefer this method. Here are some tips for improving their experience from the [Dyslexia Style Guide](https://www.bdadyslexia.org.uk/common/ckeditor/filemanager/userfiles/Dyslexia_Style_Guide_2018-final.pdf).

* Put full stops after headings to make the voice drop and pause;
* Put semi-colons, commas, or full stops after bullet points to make a pause;
* Use straight quotation marks;
* Avoid roman numerals;


## Avoid text in figures

Bookdown books allow readers to change the font style, size, and background colour. This provides essential assessibility for some people, such as those with dyslexia or visual impairments. Therefore, avoid putting too much text in figures and provide descriptions of images in the figure caption.


## Dyslexia-friendly resources

* [British Dyslexia Association](https://www.bdadyslexia.org.uk/educator);
* [Dyslexia Style Guide](https://www.bdadyslexia.org.uk/common/ckeditor/filemanager/userfiles/Dyslexia_Style_Guide_2018-final.pdf);

Some recommendations are highlighted below.

* Avoid underlining, block capitals, and italics -- Use bold instead;
* Use boxes and borders ([call-out blocks](#call-out-blocks)) for effective emphasis;
* Use left-justified with ragged right edge (don't full-justify);
* Use bullet points and numbering rather than continuous prose;
* Use the active voice with concise, direct sentences;
* Avoid abbreviations and provide a glossary of jargon;


## Sex, gender and sexuality

When teaching about experimental design, sex always used to be my go-to example of a two-level between-subjects factor. But this can make some people feel like their very existence is being ignored. In your examples, avoid implicitly assuming heterosexuality or binary gender.

If you want to suggest an in-class exercise that uses data from the students, make sure to choose something that doesn't exclude anyone. 

* Pet owners/non-pet owners;
* Normally does/doesn't wear glasses;
* Can/can't juggle;




